Azgame cog
FreeCodeCampGuam/FCCG-Cogs pull request #18
Opened 2017-02-18 03:48 UTC by jasperdanan

Too old. merge.

2017-02-23 23:35 UTC, Chovin requested changes

2017-02-23 23:35 UTC, Chovin commented on azgame/azgame.py
> +db_name = "logic.db"
what's this?

2017-02-23 23:35 UTC, Chovin commented on azgame/azgame.py
> +        c = self.bot.db.cursor()
bot doesn't have a db

2017-02-23 23:35 UTC, Chovin commented on azgame/azgame.py
> +        print("Loading words from database...")
Let's keep terminal spam to a minimum

2017-02-23 23:35 UTC, Chovin commented on azgame/azgame.py
> +        Usage: $az word"""
please use `[p]` to denote the bot's prefix. not everybody uses `$`

2017-06-10 07:58 UTC, jasperdanan commented
Cog written with Discord.py directly. Was not made for redDiscord-bot

2017-06-14 08:57 UTC, Chovin commented
This is a repo for cogs for the Red-DiscordBot. Adding this "cog" will conflict with Red's downloader. Please open a different repo if you'd like to write your own bot

2017-06-14 08:57 UTC, closed without merging